//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StasIvanBarbershop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatesVisits
    {
        public int id_Client { get; set; }
        public string Login { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Дата_первого_посещения { get; set; }
        public string Дата_последнего_посещения { get; set; }
    }
}
