//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StasIvanBarbershop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarbershopIvanEntitiesBD : DbContext
    {
        private static BarbershopIvanEntitiesBD _context;

        public static BarbershopIvanEntitiesBD GetContext()
        {
            if (_context == null)
                _context = new BarbershopIvanEntitiesBD();
            return _context;
        }
        public BarbershopIvanEntitiesBD()
            : base("name=BarbershopIvanEntitiesBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<DatesVisits> DatesVisits { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
    }
}
